platform :ios, '9.0'
use_frameworks!

target "TWNetworkManagerExample" do
	pod "TWNetworkManager", :path => "../TWNetworkManager.podspec"

	target "TWNetworkManagerExampleTests" do
		inherit! :complete
  		pod 'FBSnapshotTestCase/Core'
	end
end
