language: objective-c
osx_image: xcode7.3
before_install:
  - bundle install
  - cd Example && bundle exec pod install
script:
  - sh 'xcodebuild -workspace Example/TWNetworkManagerExample.xcworkspace -scheme \'TWNetworkManagerExample\' test -sdk iphonesimulator | xcpretty -tc; exit ${PIPESTATUS[0]}'
