language: objective-c
osx_image: xcode7.3
before_install:
  - bundle install
  - cd Example && bundle exec pod install
script:
  - xcodebuild -workspace TWNetworkManagerExample.xcworkspace -scheme 'TWNetworkManagerExample' test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' | xcpretty -tc; exit ${PIPESTATUS[0]}
